### ISSUE TITLE
Propuesta para reutilizar esta organización

### ISSUE THREAD

**Issue by astrojuanlu** [PyDataMadrid2016/Conference-Info#19]
¡Hola! @kikocorreoso ¿cómo verías

1. Renombrar https://github.com/PyDataMadrid2016 a https://github.com/PyDataMadrid,
2. Renombrar `Conference-Info` a `PyData-Madrid-2016-Conference-Info` (o algo más corto),
3. y darme acceso para crear repositorios relacionados con los meetups mensuales https://www.meetup.com/PyData-Madrid/?

Por ejemplo, estaba pensando crear uno de "presentaciones", "material" o algo así donde subir el material de las ponencias.

Si no lo ves bien, seguramente crearé https://github.com/PyDataMadrid por mi lado como organización.

**Comment by kikocorreoso** [comment]
Buenas @astrojuanlu 

Eres admin de este repo y te he mandado invitación para ser admin de la org pydata-madrid.

Por mi parte, feel free para gestionarlo como veas.

cc @guillemborrell @delapuente (por si queréis comentar algo).
